# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    session: true

    validation:
        enabled: true
        mapping:
            paths:
                - '%kernel.project_dir%/config/validator'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
