App\Entity\Location:
    properties:
        city:
            - NotBlank: { groups: [create, edit] }
            - Regex:
                  pattern: '/^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ\s\-]+$/u'
                  message: "tylko litery"
                  groups: [create, edit]
            - Length: { min: 2, max: 100, groups: [create, edit] }

        country:
            - NotBlank: { groups: [create, edit] }
            - Length: { min: 2, max: 2, groups: [create, edit] }

        latitude:
            - NotBlank: { groups: [create, edit] }
            - Type: { type: float, groups: [create, edit] }
            - Range: { min: -90, max: 90, groups: [create, edit] }

        longitude:
            - NotBlank: { groups: [create, edit] }
            - Type: { type: float, groups: [create, edit] }
            - Range: { min: -180, max: 180, groups: [create, edit] }
